"""initial schema

Revision ID: dfe7abcdd649
Revises: 
Create Date: 2026-06-26 22:39:16.504893
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dfe7abcdd649'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_case_id'), ['case_id'], unique=False)

    op.create_table('baseline_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_case_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_versions_contract_id'), ['contract_id'], unique=False)

    op.create_table('case_files',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_request', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_files_status'), ['status'], unique=False)

    op.create_table('overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('decision_index', sa.Integer(), nullable=False),
    sa.Column('system_decision', sa.String(), nullable=False),
    sa.Column('human_decision', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_overrides_case_id'), ['case_id'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overrides_case_id'))

    op.drop_table('overrides')
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_files_status'))
        batch_op.drop_index(batch_op.f('ix_case_files_project_id'))

    op.drop_table('case_files')
    with op.batch_alter_table('baseline_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_versions_contract_id'))

    op.drop_table('baseline_versions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_case_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
